server:
  contextPath: /api
  port: 9001

jwt:
 signingKey: test

# H2
flyway:
  enabled: true
  cleanOnValidationError: true

uploadPath: ~/uploadedRobots

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/robocode;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

